version: "3.7"
services:
  octo_search:
    build:
      context: .
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ".:/octo_search"
      - bundle:/bundle
    ports:
      - "3000:3000"
volumes:
  bundle:
